### PR TITLE
chore: add contributors list and update copyright tagline

### PR DESCRIPTION
**Pull request by kaf-lamed-beyt**
Addresses #111

### CODE REVIEW

**Comment by kaf-lamed-beyt** [comment]
Hi @abompard, whenever you are chanced. Please take a look at this. 

I also don't know why the DCO check keeps failing. I made sure to include the "signed-off-by..." in my format message.

**Comment by abompard** [comment]
The Signed-Off-By line should be on its own line.

**Comment by kaf-lamed-beyt** [comment]
I've updated it to be on a new line. But, it doesn't seem to cut it either. I'll follow the instructions suggested from the failure and rebase.

**Comment by kaf-lamed-beyt** [comment]
@abompard, quick question... how can i create a new line in a commit message without entering the VIM-like editor.

**Comment by abompard** [comment]
> I've updated it to be on a new line. But, it doesn't seem to cut it either. I'll follow the instructions suggested from the failure and rebase.

You can remove it from the first line of the first commit, it only needs to be in the body of the commit, not the subject (the first line is the subject, then there's an empty line, then there's the body)

You can also remove the second commit, it's unnecessary

> @abompard, quick question... how can i create a new line in a commit message without entering the VIM-like editor.

You can't, you have to use the editor. However you can use the text editor you want by setting the EDITOR environment variable. For example: `export EDITOR=nano`
For your next login, you can set environment variables in your `~/.bashrc` file.

**Comment by kaf-lamed-beyt** [comment]
Aha! I see. Thank you for clarifying. 

@abompard, I think my second commit actually passed the DCO check. If I remove it, it could result to its failure again. See the green tick in the image below

image

What do you think? Should I close this and open a new PR?

**Comment by abompard** [comment]
Your 1st commit will have to pass DCO as well, so dropping the 2nd will not change anything in that regard.

I would recommend doing a git rebase (with -i) to remove the second one and "reword" the 1st one. If you're unfamiliar with git rebase, it's worthwhile to read up on it, it's extremely useful (and powerful)

**Comment by kaf-lamed-beyt** [comment]
Now I get you. 

And thanks for mentioning git rebase too. I've heard a lot of about it, and I guess it's time for me to learn more about it now.

**Comment by kaf-lamed-beyt** [comment]
Honestly, this is good! Thank you @abompard, for recommending that I learn about `git rebase`

I read an article from Atlassian about it, and I used the `--interactive` flag like you suggested to drop the second commit. When you are chanced, please take a look at this.

**Comment by kaf-lamed-beyt** [comment]
Hi @abompard, I've updated my commit. In case you missed it.

**Review by abompard — APPROVED** [review]
Excellent, thanks!

**Comment by abompard** [comment]
Thanks for your contribution @kaf-lamed-beyt . Did you introduce yourself on [the Outreachy Fedora discussion thread](https://discussion.fedoraproject.org/t/outreachy-2024-kick-off-mentors-applicants-introduce-yourself-here/107081)?

**Comment by kaf-lamed-beyt** [comment]
Thank you for this feedback, @abompard! 

I must have missed the Fedora discussion thread. Let me go ahead and do that now.

**Pull request merged**
